spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/phonebook}?useUnicode=true&characterEncoding=utf8
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
    open-in-view: false

server:
  port: 8081